---
- name: Clone dotfiles repo
  git:
    repo: https://github.com/overtune/dotfiles.git
    dest: $HOME/.dotfiles
    bare: yes
  become_user: johrun

- name: Install oh-my-zsh. 
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: $HOME/.oh-my-zsh
  become_user: johrun

- name: Checks out the config files to home dir. 
  command: /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout 
  args:
    creates: $HOME/.vimrc
  become_user: johrun

- name: Install Vim plugins
  command: vim -E -s -c "source $HOME/.vimrc" -c PlugInstall -c qa
  args:
    creates: $HOME/.vim/plugged
  become_user: johrun

- name: Create the user Pictures dir 
  file:
    path: $HOME/pictures 
    state: directory
    mode: '0755'
  become_user: johrun

- name: Create the user Development dir 
  file:
    path: $HOME/development 
    state: directory
    mode: '0755'
  become_user: johrun
